### ISSUE TITLE
 PythonException: 'AttributeError: 'URIReference' object has no attribute 'copy_with''

### ISSUE THREAD

**Issue by jaycej1** [marksparkza/jschon#30]
When I try to use jschon inside of the udf in pyspark, I notice this error, whenever I try to `result.output("detailed")`. Is there another way I can get back the error of the validation result?

**Comment by jaycej1** [comment]
`
PythonException: 'AttributeError: 'URIReference' object has no attribute 'copy_with'', from <command-666981126211375>, line 12. Full traceback below:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 161.0 failed 4 times, most recent failure: Lost task 0.3 in stage 161.0 (TID 7941) (10.233.86.225 executor 4): org.apache.spark.api.python.PythonException: 'AttributeError: 'URIReference' object has no attribute 'copy_with'', from <command-666981126211375>, line 12. Full traceback below:
Traceback (most recent call last):
  File "<command-666981126211375>", line 15, in <lambda>
  File "<command-666981126211375>", line 12, in validatingRow
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-50c6b32b-7e0d-411e-8c0f-b1e941e5f26a/lib/python3.8/site-packages/jschon/jsonschema.py", line 491, in output
    return self.schema.catalog.output_formatter.create_output(self, format, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-50c6b32b-7e0d-411e-8c0f-b1e941e5f26a/lib/python3.8/site-packages/jschon/output.py", line 24, in create_output
    return self._basic(scope)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-50c6b32b-7e0d-411e-8c0f-b1e941e5f26a/lib/python3.8/site-packages/jschon/output.py", line 56, in _basic
    childkey: [result for result in visit(scope)],
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-50c6b32b-7e0d-411e-8c0f-b1e941e5f26a/lib/python3.8/site-packages/jschon/output.py", line 56, in <listcomp>
    childkey: [result for result in visit(scope)],
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-50c6b32b-7e0d-411e-8c0f-b1e941e5f26a/lib/python3.8/site-packages/jschon/output.py", line 48, in visit
    yield from visit(child)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-50c6b32b-7e0d-411e-8c0f-b1e941e5f26a/lib/python3.8/site-packages/jschon/output.py", line 44, in visit
    "absoluteKeywordLocation": str(node.absolute_uri),
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-50c6b32b-7e0d-411e-8c0f-b1e941e5f26a/lib/python3.8/site-packages/jschon/jsonschema.py", line 461, in absolute_uri
    return schema_uri.copy(fragment=relpath.uri_fragment())
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-50c6b32b-7e0d-411e-8c0f-b1e941e5f26a/lib/python3.8/site-packages/jschon/uri.py", line 85, in copy
    uri._uriref = self._uriref.copy_with(
AttributeError: 'URIReference' object has no attribute 'copy_with'

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:642)
	at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$2.read(PythonUDFRunner.scala:86)
	at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$2.read(PythonUDFRunner.scala:68)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:595)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:489)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:757)
	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:80)
	at org.apache.spark.sql.execution.collect.Collector.$anonfun$processFunc$1(Collector.scala:178)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:150)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:119)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:91)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:813)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1646)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:816)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:672)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2828)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2775)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2769)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2769)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1305)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1305)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1305)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3036)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2977)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2965)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1067)
	at org.apache.spark.SparkContext.runJobInternal(SparkContext.scala:2477)
	at org.apache.spark.sql.execution.collect.Collector.runSparkJobs(Collector.scala:289)
	at org.apache.spark.sql.execution.collect.Collector.collect(Collector.scala:299)
	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:82)
	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:88)
	at org.apache.spark.sql.execution.collect.InternalRowFormat$.collect(cachedSparkResults.scala:75)
	at org.apache.spark.sql.execution.collect.InternalRowFormat$.collect(cachedSparkResults.scala:62)
	at org.apache.spark.sql.execution.ResultCacheManager.$anonfun$getOrComputeResultInternal$1(ResultCacheManager.scala:510)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResultInternal(ResultCacheManager.scala:509)
	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:397)
	at org.apache.spark.sql.execution.CollectLimitExec.executeCollectResult(limit.scala:59)
	at org.apache.spark.sql.Dataset.collectResult(Dataset.scala:3041)
	at org.apache.spark.sql.Dataset.$anonfun$collectResult$1(Dataset.scala:3032)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3825)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$5(SQLExecution.scala:130)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:273)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:104)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:854)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:77)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:223)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3823)
	at org.apache.spark.sql.Dataset.collectResult(Dataset.scala:3031)
	at com.databricks.backend.daemon.driver.OutputAggregator$.withOutputAggregation0(OutputAggregator.scala:268)
	at com.databricks.backend.daemon.driver.OutputAggregator$.withOutputAggregation(OutputAggregator.scala:102)
	at com.databricks.backend.daemon.driver.PythonDriverLocalBase.generateTableResult(PythonDriverLocalBase.scala:526)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.computeListResultsItem(PythonDriverLocal.scala:674)
	at com.databricks.backend.daemon.driver.PythonDriverLocalBase.genListResults(PythonDriverLocalBase.scala:490)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.$anonfun$getResultBufferInternal$1(PythonDriverLocal.scala:729)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.withInterpLock(PythonDriverLocal.scala:610)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.getResultBufferInternal(PythonDriverLocal.scala:689)
	at com.databricks.backend.daemon.driver.DriverLocal.getResultBuffer(DriverLocal.scala:637)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.outputSuccess(PythonDriverLocal.scala:652)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.$anonfun$repl$6(PythonDriverLocal.scala:222)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.withInterpLock(PythonDriverLocal.scala:610)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.repl(PythonDriverLocal.scala:209)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$11(DriverLocal.scala:529)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:266)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:261)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:258)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:50)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:305)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:297)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:50)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:506)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:611)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:603)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommandAndGetError(DriverWrapper.scala:522)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:557)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:427)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:370)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:221)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.api.python.PythonException: 'AttributeError: 'URIReference' object has no attribute 'copy_with'', from <command-666981126211375>, line 12. Full traceback below:
Traceback (most recent call last):
  File "<command-666981126211375>", line 15, in <lambda>
  File "<command-666981126211375>", line 12, in validatingRow
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-50c6b32b-7e0d-411e-8c0f-b1e941e5f26a/lib/python3.8/site-packages/jschon/jsonschema.py", line 491, in output
    return self.schema.catalog.output_formatter.create_output(self, format, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-50c6b32b-7e0d-411e-8c0f-b1e941e5f26a/lib/python3.8/site-packages/jschon/output.py", line 24, in create_output
    return self._basic(scope)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-50c6b32b-7e0d-411e-8c0f-b1e941e5f26a/lib/python3.8/site-packages/jschon/output.py", line 56, in _basic
    childkey: [result for result in visit(scope)],
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-50c6b32b-7e0d-411e-8c0f-b1e941e5f26a/lib/python3.8/site-packages/jschon/output.py", line 56, in <listcomp>
    childkey: [result for result in visit(scope)],
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-50c6b32b-7e0d-411e-8c0f-b1e941e5f26a/lib/python3.8/site-packages/jschon/output.py", line 48, in visit
    yield from visit(child)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-50c6b32b-7e0d-411e-8c0f-b1e941e5f26a/lib/python3.8/site-packages/jschon/output.py", line 44, in visit
    "absoluteKeywordLocation": str(node.absolute_uri),
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-50c6b32b-7e0d-411e-8c0f-b1e941e5f26a/lib/python3.8/site-packages/jschon/jsonschema.py", line 461, in absolute_uri
    return schema_uri.copy(fragment=relpath.uri_fragment())
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-50c6b32b-7e0d-411e-8c0f-b1e941e5f26a/lib/python3.8/site-packages/jschon/uri.py", line 85, in copy
    uri._uriref = self._uriref.copy_with(
AttributeError: 'URIReference' object has no attribute 'copy_with'

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:642)
	at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$2.read(PythonUDFRunner.scala:86)
	at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$2.read(PythonUDFRunner.scala:68)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:595)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:489)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:757)
	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:80)
	at org.apache.spark.sql.execution.collect.Collector.$anonfun$processFunc$1(Collector.scala:178)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:150)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:119)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:91)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:813)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1646)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:816)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:672)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more`

**Comment by jaycej1** [comment]
Still getting the same error, when I check my pip install on rfc3986, it said this ```Requirement already satisfied: rfc3986==2.0.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-b3a38efa-e0be-44b6-8d0f-2d01509fdb3d/lib/python3.8/site-packages (2.0.0)
WARNING: You are using pip version 21.0.1; however, version 22.1.2 is available.
You should consider upgrading via the '/local_disk0/.ephemeral_nfs/envs/pythonEnv-b3a38efa-e0be-44b6-8d0f-2d01509fdb3d/bin/python -m pip install --upgrade pip' command.
Python interpreter will be restarted.```

**Comment by jaycej1** [comment]
This behavior only happens when I use this library in a distributed fashion, when I validate a single payload in the driver, it is fine. But I have no idea why.

**Comment by jaycej1** [comment]
Is there anyway to get back the error without calling `.output()`

**Comment by marksparkza** [comment]
> Is there anyway to get back the error without calling .output()

Short answer: No. There is not necessarily "an error". In general, there can be multiple errors at different levels and in different branches of the evaluation result tree, depending on what your schema and data look like. The `output` method does the work of recursing into the result tree and pulling out errors and annotations.

But if you're so inclined, take a look at the `jschon.output` module, and more-or-less replicate what one of the output methods does, excluding references to `absolute_uri`.

**Comment by jaycej1** [comment]
I see, I am still so confused about why the absolute_uri is none. But I guess it has to do with strange behavior with recursion inside of the spark context. I am trying to overwrite the output module, but it is more complicated than I thought. Because the Catalog class is where self.output_formatter: OutputFormatter = JSONSchemaOutputFormatter() get the outformatter, removing references to the absolute_uri. But was running into a bunch of issues, such as catalog not found. Is there any other way you think I can solve this 'AttributeError: 'URIReference' object has no attribute 'copy_with''.

**Comment by marksparkza** [comment]
Okay, let's back up a bit and try to understand why this error is happening.

jschon's URI class has a `copy` method that internally calls the `copy_with` method of the rfc3986.URIReference class. If you search for `copy` in jschon you'll see that it's used in several places. In fact it's called frequently during evaluation, so it's surprising that in your case evaluation itself does not break, only output does. What this also means is that simply patching jschon to work around this issue is not necessarily going to help - you might end up breaking core functionality rendering the library useless.

Now I went digging a little into rfc3986 and found this [commit](https://github.com/python-hyper/rfc3986/commit/bf501748f641829d57909314e029230b7e08165c) that introduced `copy_with`. This was way back in 2015. So, if you install jschon into a Python environment that already contains a pre-2015 version of rfc3986, then it will happily proceed even though it should require an upgrade. The only way I see this error happening is if one or more of your distributed nodes (specifically, the node/s on which you are calling `output`) has such an old version of rfc3986 already installed, at the point of installing jschon.

How are you installing jschon into these distributed nodes? Presumably you have a `pip install jschon` or a `jschon==0.8.5` in a config/script file somewhere? Try changing this to `pip install jschon rfc3986==2.0.0`, or adding `rfc3986==2.0.0` to your config.

**Comment by jaycej1** [comment]
<img width="579" alt="Screen Shot 2022-06-07 at 12 43 40 PM" src="https://user-images.githubusercontent.com/73313559/172437257-aad6f2ce-9458-4ccc-9a89-36ad12dab9e1.png">

Yeah, I double-check the cluster to make sure I have the right version, but still running into it. I dive deeper into the code base, could it be in this file https://github.com/marksparkza/jschon/blob/6fe69a74f75bf3a85d081f80a8a1d0a079938ce9/jschon/uri.py, that `uri_ref` object doesn't have a `copy_with` function. Maybe it is worth taking a look?

**Comment by marksparkza** [comment]
Look, here is the `copy_with` function: https://github.com/python-hyper/rfc3986/blob/164073434fe530e14ceca4ff6a0683e23e2fde48/src/rfc3986/_mixin.py#L336

If this was a general problem it would be affecting every jschon user, and most of the unit tests would be failing.

I will aim to put out a patch release in the near future to update the rfc3986 dependency requirement. If the issue persists beyond that, then it's a problem either with your application or with your runtime environment.

**Comment by jaycej1** [comment]
Hey @marksparkza , I think i figure out the issue, it is because when I use the `from jschon import create_catalog, JSON, JSONSchema

create_catalog('2020-12')

test_jschon = JSONSchema(heartbeat_schema)` in spark, to save memory I create one of this object and use that object to do all of the work, however, due to the nature of big data programs such as a spark, this object will be used at a different point through the different nodes, almost like multiple threading in a single machine. Either I need to create this object for every row, or I need to find a better way to do in batch or use another library. Closing this issue.

**Comment by marksparkza** [comment]
Thanks for the update, @jaycej1. I hope you find a suitable solution.
