### ISSUE TITLE
Cannot reproduce doc example from fresh pip install

### ISSUE THREAD

**Issue by aviv-julienjehannet** [marksparkza/jschon#9]
`% python3 -m pip install --user jschon`

```
% python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from jschon import JSONSchema
>>> int_schema = JSONSchema({"type": "integer","$schema": "https://json-schema.org/draft/2020-12/schema"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/julien/.local/lib/python3.9/site-packages/jschon/jsonschema.py", line 73, in __init__
    raise JSONSchemaError("catalogue not given and default catalogue not found")
jschon.exceptions.JSONSchemaError: catalogue not given and default catalogue not found
>>> 
```

**Comment by aviv-julienjehannet** [comment]
Ok, false positive here. It seems that the catalogue must be initialized properly before:
```
>>> Catalogue.create_default_catalogue('2020-12')
<jschon.catalogue.Catalogue object at 0x7f0866d7e550>
```
